# Generated by Django 2.2.5 on 2019-10-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voipain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(),
        ),
    ]
