# Generated by Django 2.2.5 on 2019-10-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voipain', '0002_auto_20191007_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='adress',
        ),
    ]
