# Generated by Django 2.1.1 on 2019-10-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voipain', '0003_auto_20191007_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reserver',
            field=models.BooleanField(default=False),
        ),
    ]
