# Generated by Django 2.1.1 on 2019-10-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voipain', '0004_user_reserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adressPickUp',
            field=models.CharField(default='', max_length=40),
        ),
    ]
