# Generated by Django 2.1.1 on 2019-10-10 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voipain', '0005_user_adresspickup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reserver',
            new_name='pickedUp',
        ),
    ]
